### PR TITLE
Avoid using `$` on environments that may not be R6 objects

### LINKED ISSUE #253: Issue with `$clone(deep = TRUE)` when private object has a Rcpp class
Hello,

```
> map1$clone(deep = TRUE)
Error in envRefInferField(x, what, getClass(class(x)), selfEnv) : 
  ‘.__enclos_env__’ is not a valid field or method name for reference class “uMAPR”
> class(map1$.__enclos_env__$private$.map)
[1] "uMAPR"
attr(,"package")
[1] "mapR"
> typeof(map1$.__enclos_env__$private$.map)
[1] "S4"
```

`uMAPR` is a class created with **Rcpp**:

`uMAPR <- setRcppClass("uMAPR")`

Such an object is an environment:

```
> is.environment(map1$.__enclos_env__$private$.map)
[1] TRUE
> ls(map1$.__enclos_env__$private$.map)
 [1] "callSuper"        "copy"             "erase"           
 [4] "field"            "getClass"         "getRefClass"     
 [7] "initialize"       "keys"             "merge"           
[10] "ptr"              "show"             "show#envRefClass"
[13] "size"             "usingMethods"     "values"    
```

But when you `$`-subset it with an unexisting field:

```
> map1$.__enclos_env__$private$.map$xxx
Error in envRefInferField(x, what, getClass(class(x)), selfEnv) : 
  ‘xxx’ is not a valid field or method name for reference class “uMAPR”
```

Thus the error is caused by this piece of code in `map1$clone`:

```r
      deep_clone <- function(name, value) {
        if (is.environment(value) && !is.null(value$.__enclos_env__)) {
          return(value$clone(deep = TRUE))
        }
        value
      }
```

There is no error if one replaces `!is.null(value$.__enclos_env__)` with `".__enclos_env__" %in% ls(value)`.

**cc** @eddelbuettel

By the way, there is an external pointer in this object, and the "deep clone" doesn't work: if I modify the deep clone (obtained by the above correction of `map1$clone`), the modification is also performed on the original object, because of the pointer.

Cheers.

### PR DESCRIPTION
**Pull request by zeehio**
Avoids using `$` on environments we don't control, because unexpected things may happen (such as #253). 

- Closes #253

### CODE REVIEW

File: R/clone.R [hunk 1]
```diff
@@ -89,7 +89,11 @@ generator_funs$clone_method <- function(deep = FALSE) {
       # fields that are R6 objects.
       deep_clone <- function(name, value) {
         # Check if it's an R6 object.
-        if (is.environment(value) && !is.null(value$`.__enclos_env__`)) {
+        if (
+          is.environment(value) &&
+          ".__enclos_env__" %in% ls(value, all.names = TRUE) &&
+          !is.null(get(".__enclos_env__", value))
+        ) {
```
Comment (IndrajeetPatil) [inline R/clone.R:96]: Maybe assign the complex conditional expression to a variable? 
Makes the code easier to read and also introduces a reusable abstraction.

```suggestion
        is_r6_object <- is.environment(value) &&
          ".__enclos_env__" %in% ls(value, all.names = TRUE) &&
          !is.null(get(".__enclos_env__", value))   
        if (is_r6_object) {
```

**Comment by zeehio** [comment]
Thanks @IndrajeetPatil for your review.

While reviewing this I realized this solution has a significant performance impact.

I decided to benchmark the cost of this check using four different approaches:

- `origbuggy`: The existing (buggy) solution
- `withls`: Check if `.__enclos_env__` exists using `".__enclos_env__" %in% ls(value, all.names = TRUE)`
- `withnames`: Check if `.__enclos_env__` exists using `".__enclos_env__" %in% names(value)`
- `rlang_envget`: Check using `!is.null(rlang::env_get(env = value, nm = ".__enclos_env__", default = NULL)`

Since the size of the environment has an impact, I tested results with two environment sizes:

- `1it`: An environment with one item
- `100kit`: An environment with 100 000 items

Since the performance may be different, due to method dispatch, depending on whether the environment has a `class` attribute or not I checked:

- `classed`: The environment has a `class` attribute
- `notclassed`: The environment does not have a `class` attribute

My conclusion after all this testing is that the option with less impact and better scaling would depend on introducing an `rlang` dependency, or possibly borrowing some compiled code from `rlang`. Since we want R6 objects to be fully self-contained, we can't possibly introduce that dependency.

Therefore so far I have updated the current solution to use `names()` instead.

The combinations explode rather fast, but I microbenchmarked all those solutions and produced the following reprex:


``` r
library(rlang)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)
library(tidyr)


create_env_with_items <- function(nitems = 1000, class. = NULL) {
  e <- new.env(parent = emptyenv())
  for (i in seq_len(nitems)) {
    e[[paste0("A", as.character(i))]] <- runif(1)
  }
  if (!is.null(class.)) {
    class(e) <- class.
  }
  e
}

env_with_class_1item <- create_env_with_items(1, "bar")
env_without_class_1item <- create_env_with_items(1)

env_with_class_100000item <- create_env_with_items(100000, "bar2")
env_without_class_100000item <- create_env_with_items(100000)


orig_buggy <- function(value) {
  is.environment(value) &&
    !is.null(value$`.__enclos_env__`)
}

with_ls <- function(value) {
  is.environment(value) &&
    ".__enclos_env__" %in% ls(value, all.names = TRUE) &&
    !is.null(value$`.__enclos_env__`)
}

with_names <- function(value) {
  is.environment(value) &&
    ".__enclos_env__" %in% names(value) &&
    !is.null(value$`.__enclos_env__`)
}

with_rlang_envget <- function(value) {
  is.environment(value) &&
    !is.null(env_get(env = value, nm = ".__enclos_env__", default = NULL))
}


mb <- microbenchmark::microbenchmark(
  origbuggy_notclassed_1it = orig_buggy(env_without_class_1item),
  origbuggy_classed_1it = orig_buggy(env_with_class_1item),
  withls_notclassed_1it = with_ls(env_without_class_1item),
  withls_classed_1it = with_ls(env_with_class_1item),
  withnames_notclassed_1it = with_names(env_without_class_1item),
  withnames_classed_1it = with_names(env_with_class_1item),
  rlang_notclassed_1it = with_rlang_envget(env_without_class_1item),
  rlang_classed_1it = with_rlang_envget(env_with_class_1item),
  origbuggy_notclassed_100kit = orig_buggy(env_without_class_100000item),
  origbuggy_classed_100kit = orig_buggy(env_with_class_100000item),
  withls_notclassed_100kit = with_ls(env_without_class_100000item),
  withls_classed_100kit = with_ls(env_with_class_100000item),
  withnames_notclassed_100kit = with_names(env_without_class_100000item),
  withnames_classed_100kit = with_names(env_with_class_100000item),
  rlang_notclassed_100kit = with_rlang_envget(env_without_class_100000item),
  rlang_classed_100kit = with_rlang_envget(env_with_class_100000item)
)
mb
#> Unit: nanoseconds
#>                         expr       min          lq         mean      median
#>     origbuggy_notclassed_1it       484      1285.0      6013.11      2611.0
#>        origbuggy_classed_1it      1289      5864.0     13071.18     10746.0
#>        withls_notclassed_1it      9332     32106.5     46210.44     48054.0
#>           withls_classed_1it     10125     22191.5     89244.86     46614.0
#>     withnames_notclassed_1it      1556      3607.5      7358.21      5557.5
#>        withnames_classed_1it      2229      8870.5     16360.43     13422.0
#>         rlang_notclassed_1it      5050     11348.5     26515.13     16582.0
#>            rlang_classed_1it      5143     10712.0     56625.65     26728.0
#>  origbuggy_notclassed_100kit       524      1333.5      5671.53      2536.5
#>     origbuggy_classed_100kit      1059      5550.5     50697.60     10716.0
#>     withls_notclassed_100kit 664157088 707756871.0 733830967.35 729148772.5
#>        withls_classed_100kit 648637058 689592877.5 722970460.34 722223217.5
#>  withnames_notclassed_100kit  28377607  32144577.5  36354930.76  36717967.5
#>     withnames_classed_100kit  21224049  24350499.5  29156909.30  29113668.5
#>      rlang_notclassed_100kit      5703      9264.5     25494.00     16473.0
#>         rlang_classed_100kit      4967     11629.5     29231.22     28226.0
#>           uq       max neval
#>      10270.5     31128   100
#>      18552.0     31553   100
#>      59158.0    136071   100
#>      57535.0   4577587   100
#>       9575.5     25663   100
#>      21809.5     60051   100
#>      36653.5    113235   100
#>      42478.5   2918142   100
#>       5383.0     32052   100
#>      20985.5   3718767   100
#>  756856515.0 884545987   100
#>  745516539.0 881271426   100
#>   39395112.5  48840725   100
#>   32613951.0  47580453   100
#>      41772.5     73733   100
#>      44075.0     73064   100

mbdf <- as.data.frame(mb) %>%
  separate(expr, c("method", "klass", "size"), remove = FALSE)

method_colors <- scales::brewer_pal("qual")(length(unique(mbdf$method)))
names(method_colors) <- unique(mbdf$method)

ggplot(mbdf) +
  geom_boxplot(aes(x = forcats::fct_reorder2(expr, klass, size), y = time, fill= method)) +
  scale_fill_manual(values = method_colors) +
  labs(x = "Method") +
  coord_flip()
```



``` r

# Let's exclude with_ls since it's clearly worse

mbdf_nols <- filter(mbdf, method != "withls")
ggplot(mbdf_nols) +
  geom_boxplot(aes(x = forcats::fct_reorder2(expr, klass, size), y = time, fill= method)) +
  scale_fill_manual(values = method_colors) +
  labs(x = "Method") +
  coord_flip()
```



``` r

# Next worse option is withnames:


mbdf_nols_nonames <- filter(mbdf_nols, method != "withnames")
ggplot(mbdf_nols_nonames) +
  geom_boxplot(aes(x = forcats::fct_reorder2(expr, klass, size), y = time, fill= method)) +
  scale_fill_manual(values = method_colors) +
  labs(x = "Method") +
  coord_flip(ylim = c(0, 2E5))
```



``` r

# The best option is using rlang, but we can't introduce such dependency.
```

<sup>Created on 2023-04-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

File: R/clone.R (hunk 1 above)
Comment (zeehio) [reply R/clone.R]: While applying your suggestion I realized `ls(value, all.names = TRUE)` had a huge performance impact (the check was at least one order of magnitude slower, and it did not scale great with the number of elements in `value` for our use case).

So I tried several alternatives (`ls`, `names`, `rlang::env_get`) without success until I finally found `get0()` which is in base R since R 3.2 and it is just what we needed.

Thanks for your suggestion, it helped me realize of this other problem and address it.

I believe the patch can now safely be merged.

File: tests/testthat/test-clone.R [hunk 2]
```diff
@@ -1077,6 +1077,28 @@ test_that("Cloning inherited methods for non-portable classes", {
   expect_identical(a$x, 3)
 })
 
+test_that("Unknown environments are not copied nor $-inspected", {
```
Comment (wch) [inline tests/testthat/test-clone.R:1080]:
```suggestion
test_that("In deep_clone(), don't try to clone non-R6 objects", {
```

File: tests/testthat/test-clone.R [hunk 3]
```diff
@@ -1077,6 +1077,28 @@ test_that("Cloning inherited methods for non-portable classes", {
...
+
+  `$.asdfasdf` <- function(x, value) {
```
Comment (wch) [inline tests/testthat/test-clone.R:1082]: This is a minor, but this name makes it feel like the code is random text typed at the console. Can you rename it to something like `$.test`?

File: tests/testthat/test-clone.R [hunk 4]
```diff
@@ -1077,6 +1077,28 @@ test_that("Cloning inherited methods for non-portable classes", {
...
+                 public = list(
+                   x = NULL,
+                   initialize = function() {
+                     x <- new.env(parent = emptyenv())
+                     class(x) <- "asdfasdf"
+                     self$x <- x
+                     x
+                   }
+                 )
+  )
```
Comment (wch) [inline tests/testthat/test-clone.R:1096]: Please indent like the rest of the code in these tests.

File: tests/testthat/test-clone.R [hunk 5]
```diff
@@ -1077,6 +1077,28 @@ test_that("Cloning inherited methods for non-portable classes", {
...
+  }
+
+  bar <- R6Class("bar",
+                 public = list(
+                   x = NULL,
+                   initialize = function() {
+                     x <- new.env(parent = emptyenv())
+                     class(x) <- "asdfasdf"
+                     self$x <- x
+                     x
```
Comment (wch) [inline tests/testthat/test-clone.R:1093]: No need to return `x`

File: tests/testthat/test-clone.R [hunk 6]
```diff
@@ -1077,6 +1077,28 @@ test_that("Cloning inherited methods for non-portable classes", {
...
+                   }
+                 )
+  )
+
+  obj <- bar$new()
+  obj2 <- obj$clone(deep = TRUE)
+  expect_equal(obj$x, obj2$x)
```
Comment (wch) [inline tests/testthat/test-clone.R:1100]: I think this should be `expect_identical`?

```
x <- new.env()
y <- new.env()

expect_equal(x, y) # Passes

expect_identical(x, y)
#> Error: `x` not identical to `y`.
#> Objects equal but not identical
```

File: tests/testthat/test-clone.R (hunk 3 above)
Comment (zeehio) [reply tests/testthat/test-clone.R]: Done

File: tests/testthat/test-clone.R (hunk 4 above)
Comment (zeehio) [reply tests/testthat/test-clone.R]: Done

File: tests/testthat/test-clone.R (hunk 6 above)
Comment (zeehio) [reply tests/testthat/test-clone.R]: Done

File: tests/testthat/test-clone.R [hunk 7]
```diff
@@ -1077,6 +1077,28 @@ test_that("Cloning inherited methods for non-portable classes", {
   expect_identical(a$x, 3)
 })
 
+test_that("In deep_clone(), don't try to clone non-R6 objects", {
+
+  `$.asdfasdf` <- function(x, value) {
+    stop("error")
+  }
+
+  bar <- R6Class("bar",
```
[the remark this answers is not in the document]
Comment (zeehio) [reply tests/testthat/test-clone.R]: and done

**Comment by zeehio** [comment]
Thanks for the review @wch. I took care of all of your suggestions without any issues
