### PR TITLE
Fix cloning inheritance

### LINKED ISSUE #165: Subclasses should inherit value of 'cloneable' by default

### LINKED ISSUE #247: FR: Support subclass to override superclass' cloning method
Let's say I have a class called `Creature`. I wish to provide a `$clone()` method for this class, so I set `cloneable = TRUE`, and it works as expected:

``` r
library(R6)

# define a class
Creature <- R6Class(
  "Creature",
  cloneable = TRUE
)

# cloning for class objects possible
Creature$new()$clone()
#> <Creature>
#>   Public:
#>     clone: function (deep = FALSE)
```

Now, let's say I create a subclass `Human` that inherits from `Creature`. For this class, I don't want to provide `$clone()` method. So I set `cloneable = FALSE`, but that doesn't work:

```r
# create a subclass
Human <- R6Class(
  "Human",
  inherit = Creature,
  cloneable = FALSE
)

# cloning still possible even when
# `cloneable` is set to `FALSE`
Human$new()$clone()
#> <Human>
#>   Inherits from: <Creature>
#>   Public:
#>     clone: function (deep = FALSE)
```

<sup>Created on 2022-03-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

Is it possible for `{R6}` to support this?

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
Closes #247
Closes #165

## Example

``` r
library(R6)

Creature <- R6Class("Creature", cloneable = TRUE)

Sheep <- R6Class("Sheep", inherit = Creature, cloneable = TRUE)
sheep <- Sheep$new()
class(sheep$clone())
#> [1] "Sheep"    "Creature" "R6"

Human <- R6Class("Human", inherit = Creature, cloneable = FALSE)
human <- Human$new()
human$clone()
#> Error in eval(expr, envir, enclos): attempt to apply non-function

Creature <- R6Class("Creature", cloneable = FALSE)

Sheep <- R6Class("Sheep", inherit = Creature, cloneable = TRUE)
sheep <- Sheep$new()
#> Subclass wants to allow cloning, but superclass has turned it off. Therefore, cloning will also be turned off for subclass.
class(sheep$clone())
#> Error in eval(expr, envir, enclos): attempt to apply non-function

Human <- R6Class("Human", inherit = Creature, cloneable = FALSE)
human <- Human$new()
human$clone()
#> Error in eval(expr, envir, enclos): attempt to apply non-function
```

<sup>Created on 2022-10-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

File: R/new.R [hunk 1]
```diff
@@ -13,6 +13,15 @@ generator_funs$new <- function(...) {
     if (!identical(portable, inherit$portable))
       stop("Sub and superclass must both be portable or non-portable.")
 
+    if (!identical(cloneable, inherit$cloneable)) {
+      message(c(
```
Comment (IndrajeetPatil) [inline R/new.R:17]: I think this should be a message and not a warning, since, in some contexts, such a mismatch is unavoidable.

File: tests/testthat/test-cloning-inheritance.R [hunk 2]
```diff
@@ -0,0 +1,27 @@
+test_that("Subclass can override superclass' cloneable property", {
```
Comment (IndrajeetPatil) [inline tests/testthat/test-cloning-inheritance.R:1]: Happy to move these tests to `test-clone.R`, if needed.

**Comment by wch** [comment]
If I understand correctly, this will change the default behavior so that if someone creates a subclass and does _not_ explicitly specify a value for `cloneable`, then:
- Previously, the subclass would not be cloneable.
- With this change, the subclass would be cloneable.

Am I understanding this correctly?

**Comment by IndrajeetPatil** [comment]
That's correct.

If `cloneable` is not specified for superclass, then the default behaviour remains the same.

``` r
library(R6)

Creature <- R6Class("Creature")
Sheep <- R6Class("Sheep", inherit = Creature)
Sheep$new()
#> <Sheep>
#>   Inherits from: <Creature>
#>   Public:
#>     clone: function (deep = FALSE)
``` 

But, if it is set to `FALSE`, then the default behaviour changes with this PR. Now, the subclass would override superclass setting because there is a mismatch. 

``` r
Creature <- R6Class("Creature", cloneable = FALSE)
Sheep <- R6Class("Sheep", inherit = Creature)
Sheep$new()
#> Sub and superclass have different cloneable properties. Subclass property will override superclass property.
#> <Sheep>
#>   Inherits from: <Creature>
#>   Public:
#>     clone: function (deep = FALSE)
```

<sup>Created on 2022-10-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I'd run a revdepcheck to see how many deps are affected by this, but `{R6}` has many deps, and I don't think my desktop can handle it.

I am open to suggestions on how to let the subclass override subclass cloning property when there is a mismatch, but in a backward-compatible manner.

**Comment by wch** [comment]
Some thoughts:

- When the superclass has `cloneable=F`, it is dangerous for a subclass to have `cloneable=T`. The option `cloneable=FALSE` must be set explicitly, and I'd expect that the author of the superclass would do this for a good reason -- for example, the object may represent some external resource, or it may contain reference objects.
- When the superclass has `cloneable=T`, it can make sense for a subclass to have `cloneable=FALSE`.
- It would be better if the subclass inherited the `cloneable` property by default, instead of defaulting to `TRUE`. I'm not sure of the best way to do this right offhand. Maybe with some sort of sentinel value.

**Comment by IndrajeetPatil** [comment]
@wch I've addressed the first two points. 

- When super has turned off cloning, cloning will always be off for subclasses, irrespective of what `cloneable` is set to.
- If super allow cloning, then the `cloneable` property set for sub will be respected.

``` r
library(R6)

# superclass non-cloneable  ---------------------

Creature <- R6Class("Creature", cloneable = FALSE)

Sheep <- R6Class("Sheep", inherit = Creature, cloneable = TRUE)
sheep <- Sheep$new()
#> Subclass wants to allow cloning, but superclass has turned it off. Therefore, cloning will also be turned off for subclass.
class(sheep$clone())
#> Error in eval(expr, envir, enclos): attempt to apply non-function

Human <- R6Class("Human", inherit = Creature, cloneable = FALSE)
human <- Human$new()
human$clone()
#> Error in eval(expr, envir, enclos): attempt to apply non-function

# superclass cloneable  ---------------------

Creature <- R6Class("Creature", cloneable = TRUE)

Sheep <- R6Class("Sheep", inherit = Creature, cloneable = TRUE)
sheep <- Sheep$new()
class(sheep$clone())
#> [1] "Sheep"    "Creature" "R6"

Human <- R6Class("Human", inherit = Creature, cloneable = FALSE)
human <- Human$new()
human$clone()
#> Error in eval(expr, envir, enclos): attempt to apply non-function
```

<sup>Created on 2022-10-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Addressing the third point in this PR feels like expanding its scope. I am also hesitant to work on it because I am not sure what the expected API change looks like (should default be `NULL`, `FALSE`, `NA`, etc.?), or what impact it might have.

File: R/new.R [hunk 3]
```diff
@@ -13,6 +13,24 @@ generator_funs$new <- function(...) {
...
+    if (!identical(cloneable, inherit$cloneable)) {
+      if (inherit$cloneable) {
+        inherit[["public_methods"]][["clone"]] <- NULL
+      }
+
+      if (!inherit$cloneable) {
+        message(c(
+          "Subclass wants to allow cloning, but superclass has turned it off. ",
+          "Therefore, cloning will also be turned off for subclass."
+        ))
```
Comment (IndrajeetPatil) [inline R/new.R:28]: Placeholder. Can be tweaked further.

**Comment by wch** [comment]
I think that the way you addressed the first two points actually solves the third point.

File: NEWS.md [hunk 4]
```diff
@@ -5,7 +5,7 @@ R6 2.5.1.9000
 
 * `R6Class()` now prints a message when a `finalize` method is public instead of private.
 
-* When subclass' `cloneable` property differs from superclass', the former will override the latter (@IndrajeetPatil, #247).
+* When subclass allows cloning, while superclass has turned cloning off, superclass will override subclass' cloning properties. (@IndrajeetPatil, #247).
```
Comment (wch) [inline NEWS.md:8]: How about:

> When a superclass is not cloneable, then subclasses cannot be cloneable.

File: R/new.R [hunk 5]
```diff
@@ -13,13 +13,22 @@ generator_funs$new <- function(...) {
...
+    # If `cloneable` property differs between sub and superclass
+    # - super will override sub if super doesn't allow cloning
+    # - sub will override super if super allows cloning
     if (!identical(cloneable, inherit$cloneable)) {
-      message(c(
-        "Sub and superclass have different cloneable properties. ",
-        "Subclass property will override superclass property."
-      ))
+      if (inherit$cloneable) {
+        inherit[["public_methods"]][["clone"]] <- NULL
```
Comment (wch) [inline R/new.R:21]: I think this will _modify_ the superclass, which is bad.

File: R/new.R (hunk 3 above)
Comment (wch) [reply R/new.R:28]: I suggest including the name of the classes in the message, with something like:

> Superclass XX has cloneable=FALSE, but subclass YY has cloneable=TRUE. A subclass cannot be cloneable when its superclass is not cloneable, so cloning will be disabled for YY.

Also `message()` doesn't need `c()` inside of it.

File: R/new.R [hunk 6]
```diff
@@ -13,13 +13,22 @@ generator_funs$new <- function(...) {
...
+      }
+
+      if (!inherit$cloneable) {
```
Comment (wch) [inline R/new.R:24]: This could be an `else` statement.

File: R/new.R (hunk 5 above)
Comment (IndrajeetPatil) [reply R/new.R:21]: Ah, good catch!

I have added a test for this, which is going to fail for now. Will revisit this tomorrow.

Comment (IndrajeetPatil) [reply R/new.R]: This is now fixed.

File: R/new.R [hunk 7]
```diff
@@ -103,6 +103,20 @@ generator_funs$new <- function(...) {
...
+
+    # If `cloneable` property differs between sub and superclass
+    # - super will override sub if super doesn't allow cloning
+    # - sub will override super if super allows cloning
+    if (!identical(cloneable, inherit$cloneable)) {
+      public_methods[["clone"]] <- NULL
+
+      if (!inherit$cloneable) {
+        message(
+          "Superclass ", get_superclassnames(inherit), " has cloneable=FALSE, but subclass ", classname, " has cloneable=TRUE. ",
```
Comment (wch) [inline R/new.R:115]: `get_superclassnames(inherit)` will return a vector of class names, which will won't print out well. I think that `inherit$classname` will work better.

File: tests/testthat/test-cloning-inheritance.R [hunk 8]
```diff
@@ -0,0 +1,29 @@
...
+  expect_true("clone" %in% names(Creature$public_methods))
+
+  # superclass non-cloneable  ---------------------
+
+  Creature <- R6Class("Creature", cloneable = FALSE)
+
+  Sheep <- R6Class("Sheep", inherit = Creature, cloneable = TRUE)
+  expect_message(sheep <- Sheep$new(), "Superclass Creature has cloneable=FALSE, but subclass Sheep has cloneable=TRUE.")
+  expect_error(sheep$clone(), "attempt to apply non-function")
+  expect_false("clone" %in% names(Creature$public_methods))
```
Comment (wch) [inline tests/testthat/test-cloning-inheritance.R:23]:
```suggestion
  # Make sure that the superclass wasn't inadvertantly modified.
  expect_false("clone" %in% names(Creature$public_methods))
```

**Review by wch — APPROVED** [review]
Looks good!

**Comment by ColinFay** [comment]
Hello,

I reached this PR because I stumbled upon the behavior it corrects. 

Any plan on releasing this version to CRAN? 

Thanks

**Comment by wch** [comment]
@ColinFay The new version of R6, 2.6.0, is on CRAN.
